# security:
#     providers:
#         in_memory:
#             memory: ~

#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#             security: false

#         default:
#             anonymous: ~
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$nRUgVEe9nCKjzYrwjebFeeqOPElS5V4W2Y0c1VUmwoQ.SzChK/.j.
                        roles: 'ROLE_ADMIN'

    # role_hierarchy:
    #     ROLE_ADMIN: ROLE_CFA

    # providers:
    #     administrators:
    #         entity: { class: WeddingManageBundle:Login, property: username }

    # firewalls:
    #     dev:
    #         pattern:  ^/(_(profiler|wdt)|css|images|js)/
    #         security: false

    #     demo_login:
    #         pattern:  ^/demo/secured/login$
    #         security: false

    #     demo_secured_area:
    #         pattern:    ^/demo/secured/
    #         form_login:
    #             check_path: _demo_security_check
    #             login_path: _demo_login
    #         logout:
    #             path:   _demo_logout
    #             target: _demo

    #     secured_area:
    #         pattern: ^/admin
    #         anonymous: ~
    #         form_login:
    #             login_path: login
    #             check_path: login_check
    #         logout:
    #             path:   /logout
    #             target: /
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
        secured_area:
            pattern: ^/
            anonymous: ~
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
